---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo
spec:
  replicas: 1
  strategy: { type: Recreate }
  template:
    spec:
      serviceAccountName: pgo
      containers:
      - name: operator
        image: postgres-operator
        env:
        - name: PGO_INSTALLER
          value: kustomize
        - name: PGO_INSTALLER_ORIGIN
          value: customer-portal
        - name: PGO_NAMESPACE
          valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
        - name: CRUNCHY_DEBUG
          value: "true"
        - name: RELATED_IMAGE_POSTGRES_12
          value: image-crunchy-postgres-12
        - name: RELATED_IMAGE_POSTGRES_12_GIS_3.0
          value: image-crunchy-postgres-12-gis-3.0
        - name: RELATED_IMAGE_POSTGRES_12_GIS_2.5
          value: image-crunchy-postgres-12-gis-2.5
        - name: RELATED_IMAGE_POSTGRES_13
          value: image-crunchy-postgres-13
        - name: RELATED_IMAGE_POSTGRES_13_GIS_3.1
          value: image-crunchy-postgres-13-gis-3.1
        - name: RELATED_IMAGE_POSTGRES_13_GIS_3.0
          value: image-crunchy-postgres-13-gis-3.0
        - name: RELATED_IMAGE_POSTGRES_14
          value: image-crunchy-postgres-14
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.3
          value: image-crunchy-postgres-14-gis-3.3
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.2
          value: image-crunchy-postgres-14-gis-3.2
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.1
          value: image-crunchy-postgres-14-gis-3.1
        - name: RELATED_IMAGE_POSTGRES_15
          value: image-crunchy-postgres-15
        - name: RELATED_IMAGE_POSTGRES_15_GIS_3.3
          value: image-crunchy-postgres-15-gis-3.3
        - name: RELATED_IMAGE_POSTGRES_16
          value: image-crunchy-postgres-16
        - name: RELATED_IMAGE_POSTGRES_16_GIS_3.3
          value: image-crunchy-postgres-16-gis-3.3
        - name: RELATED_IMAGE_POSTGRES_16_GIS_3.4
          value: image-crunchy-postgres-16-gis-3.4
        - name: RELATED_IMAGE_PGADMIN
          value: image-pgadmin-v4
        - name: RELATED_IMAGE_PGBACKREST
          value: image-pgbackrest
        - name: RELATED_IMAGE_PGBOUNCER
          value: image-pgbouncer
        - name: RELATED_IMAGE_PGEXPORTER
          value: image-postgres-exporter
        - name: RELATED_IMAGE_PGUPGRADE
          value: image-crunchy-upgrade
        - name: RELATED_IMAGE_STANDALONE_PGADMIN
          value: image-pgadmin
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities: { drop: [ALL] }
          readOnlyRootFilesystem: true
          runAsNonRoot: true
